Add Home Assistant MQTT discovery
thanksmister/wallpanel-android pull request #233
Opened 2021-01-09 23:57 UTC by MarkGodwin

This adds [MQTT Discovery](https://www.home-assistant.io/docs/mqtt/discovery/)to the MQTT channel for the sensors on the wall panel. So you don't have to do anything in HA config for the wall panel devices to appear.
![image](https://user-images.githubusercontent.com/10632972/104111014-6d49d900-52d5-11eb-8116-28c9414eaa02.png)

Sorry, I don't know Kotlin or Android development, so there would probably be some cleaner ways to implement this. I also had to create a new version of publish, which didn't fill me with joy.

I had to re-order the calls to `listener?.handleMqttConnected()` because the attempts to publish to MQTT in the handler were being blocked.

I added a couple of settings to control the HA MQTT Discovery settings. They will be disabled by default.

2021-01-13 21:44 UTC, thanksmister commented
We have to do some refactoring on this.  I have to find time to go over and rewrite the code.

2021-01-14 00:18 UTC, MarkGodwin commented
I’m happy to put more polish into it if you want to kick it back for any reason.

2021-01-15 18:44 UTC, thanksmister commented
> I’m happy to put more polish into it if you want to kick it back for any reason.
> 
> Like killing off publishEx, for example...

yes exactly, if we can clean that up and try to reuse, but its not 100% necessary.  If you require another methods, that's ok.  I do not like the name, maybe more descriptive at least.

2021-01-15 18:44 UTC, thanksmister commented on WallPanelApp/src/main/java/com/thanksmister/iot/wallpanel/modules/MQTTModule.kt
> +    fun publishEx(topic: String, message : String, retain: Boolean) {
Better name would be prefered.

2021-01-15 18:46 UTC, thanksmister commented on WallPanelApp/src/main/java/com/thanksmister/iot/wallpanel/network/MQTTService.kt
> +        if(mqttOptions != null) {
mqttOptions?.let { }

2021-01-15 18:48 UTC, thanksmister commented on WallPanelApp/src/main/java/com/thanksmister/iot/wallpanel/network/WallPanelService.kt
> +            val batteryDiscovery = getSensorDiscoveryDef("Battery Level", "sensor/battery", "battery", "%", "battery")
Strings should go into the string resources folder.

2021-01-15 18:50 UTC, thanksmister commented on WallPanelApp/src/main/java/com/thanksmister/iot/wallpanel/network/WallPanelService.kt
> +            //publishMessageEx( "homeassistant/binary_sensor/${configuration.mqttClientId}/acPlugged/config", "", false)
What happened to ac plugged?

2021-01-15 18:53 UTC, thanksmister commented on WallPanelApp/src/main/java/com/thanksmister/iot/wallpanel/persistence/Configuration.kt
> +                R.string.default_setting_mqtt_basetopic).trimEnd('/') + "/"
I don't think we should do this, if user updates the base, then sees the appended "/" they could think this is a bug.   We should respect user's input and add the "/" as needed before we make the call.

2021-01-15 18:55 UTC, thanksmister requested changes

2021-01-15 18:55 UTC, thanksmister commented on WallPanelApp/src/main/java/com/thanksmister/iot/wallpanel/ui/fragments/MqttSettingsFragment.kt
> +        mqttHomeAssistantDiscovery = findPreference<SwitchPreference>(getString(R.string.key_setting_mqtt_home_assistant_discovery)) as SwitchPreference
Let's not use Home Assistant in the application or for names.  MQTT is generic for all home automation platforms.  So this discovery could work for Node Red as well.  I would just remove HomeAssistant home_assistant and leave discovery.

2021-01-18 11:33 UTC, MarkGodwin commented
I'll tackle these and get back to you in a day or two. I want to collapse `publish` and `publishEx` into a single function, but that means moving responsibility of setting the base topic outside of the MQTT service class, and into the callers. Shout if that's not acceptable to you.

2021-01-18 11:36 UTC, MarkGodwin commented on WallPanelApp/src/main/java/com/thanksmister/iot/wallpanel/ui/fragments/MqttSettingsFragment.kt
> +        mqttHomeAssistantDiscovery = findPreference<SwitchPreference>(getString(R.string.key_setting_mqtt_home_assistant_discovery)) as SwitchPreference
I think the discovery format we are using _is_ Home Assistant specific, although I guess other automation platforms may support it. But I'll change the name.
I'll also add a discovery base topic setting, as "homeassistant" is only a default setting, and it can be changed in HA.

2021-01-18 11:37 UTC, MarkGodwin commented on WallPanelApp/src/main/java/com/thanksmister/iot/wallpanel/persistence/Configuration.kt
> +                R.string.default_setting_mqtt_basetopic).trimEnd('/') + "/"
Sure, I was being lazy, as I'm not familiar with the kotlin framework libraries.

2021-01-18 11:39 UTC, MarkGodwin commented on WallPanelApp/src/main/java/com/thanksmister/iot/wallpanel/network/WallPanelService.kt
> +            //publishMessageEx( "homeassistant/binary_sensor/${configuration.mqttClientId}/acPlugged/config", "", false)
Does anyone have a tablet with an AC power supply? 😀 
I actually left this off for myself, didn't mean to leave it out of the PR.

2021-01-18 11:52 UTC, thanksmister commented on WallPanelApp/src/main/java/com/thanksmister/iot/wallpanel/ui/fragments/MqttSettingsFragment.kt
> +        mqttHomeAssistantDiscovery = findPreference<SwitchPreference>(getString(R.string.key_setting_mqtt_home_assistant_discovery)) as SwitchPreference
I think it will work with other platforms, I just prefer the naing to be non-specific, so instead of mqttHomeAssistantDiscovery, we use mqttDiscovery or mqttAlarmDiscovery.

2021-01-18 11:53 UTC, thanksmister commented on WallPanelApp/src/main/java/com/thanksmister/iot/wallpanel/ui/fragments/MqttSettingsFragment.kt
> +        mqttHomeAssistantDiscovery = findPreference<SwitchPreference>(getString(R.string.key_setting_mqtt_home_assistant_discovery)) as SwitchPreference
Yeah not thrilled with  "homeassistant" as the base topic, for the same reason, to be generic.  However, if this is the default in HA, then that is fine, users can change it for other platforms.

2021-01-18 11:54 UTC, thanksmister commented on WallPanelApp/src/main/java/com/thanksmister/iot/wallpanel/network/WallPanelService.kt
> +            //publishMessageEx( "homeassistant/binary_sensor/${configuration.mqttClientId}/acPlugged/config", "", false)
POE?  If we have access to it, sure let's publish it.  However its not important, remove commented out code if you choose not to include it.

2021-01-18 12:10 UTC, thanksmister commented
Do we still need to publish sensor data if we have now made them discoverable?   Seems we should have another option in the sensors section.  User's can wish to publish sensors, then select either manual publish (current behavior) or make them discoverable, but not both?

2021-01-18 20:13 UTC, MarkGodwin commented
Not sure I follow you. The discovery entries just tell HA where to find the right topics for the published sensor data. We still need to publish the sensor data somewhere else.

2021-01-18 20:16 UTC, thanksmister commented
> Not sure I follow you. The discovery entries just tell HA where to find the right topics for the published sensor data. We still need to publish the sensor data somewhere else.

Yeah, sorry, you're right was just thinking about the current published sensors, we need to match what we publish now right?

2021-01-18 21:07 UTC, MarkGodwin commented
Yeah, so we clear out the discovery info by sending an empty string for the sensors that are disabled in config. Otherwise you have to remove them manually in HA (which does the same thing).

2021-01-18 22:16 UTC, MarkGodwin commented on WallPanelApp/src/main/java/com/thanksmister/iot/wallpanel/network/WallPanelService.kt
> +            val batteryDiscovery = getSensorDiscoveryDef("Battery Level", "sensor/battery", "battery", "%", "battery")
Good point. I've moved all the  display names to the strings file for L10N.

2021-01-29 13:02 UTC, merged

2021-01-29 18:03 UTC, thanksmister commented
@MarkGodwin do we need to have the discovery topic be "homeassistant"  I did not see information in the MQTT Discovery documentation about how home assistant detects things.  I recall you maybe told me this needs to be `homeassistant` and that HA looks for this topic for discovery?

2021-01-29 21:44 UTC, MarkGodwin commented
It's documented [here](https://www.home-assistant.io/docs/mqtt/discovery/). 

The default is `homeassistant`, but you can set the `discovery_prefix` to change it. You have to edit the configuration.yaml file, so I doubt many people ever would. I think the format of the discovery is very specific to Home Assistant, but it's quite possible that other hubs with MQTT support might interpret the same data.